server.port=8093

userservice.host=${USER_SERVICE_HOST:userservice.userservicenamespace}
userservice.path=/users

pointservice.host=${POINT_SERVICE_HOST:pointservice-svc.psn}
pointservice.path=/point/users



